import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig } from "tsdown";

// Build-time version injection. The published artifact bakes in the real
// SDK_VERSION (from package.json, synced from the release tag) and SPEC_VERSION
// (from a committed file generated by `bun run codegen`), so there is no manual
// sed step and no `process` reference in the shipped bundle. Reading the spec
// version from the committed file rather than ../api-spec keeps the build
// self-contained, so the public mirror builds standalone. Local dev/tests fall
// back to the "0.0.0" placeholder in src/version.ts. See sdk-release.yml.
const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(
  readFileSync(resolve(here, "package.json"), "utf8"),
) as { version: string };
const spec = JSON.parse(
  readFileSync(resolve(here, "src/generated/spec.version.json"), "utf8"),
) as { specVersion: string };

// Builds the publishable artifact: ESM (index.mjs) + CJS (index.cjs) + type
// declarations + sourcemaps. Zero runtime deps, so the bundle is self-contained.
export default defineConfig({
  clean: true,
  define: {
    "process.env.EXPYS_SDK_VERSION": JSON.stringify(pkg.version),
    "process.env.EXPYS_SPEC_VERSION": JSON.stringify(spec.specVersion),
  },
  dts: true,
  entry: ["src/index.ts"],
  format: ["esm", "cjs"],
  outDir: "dist",
  // Keep TSDoc out of the runtime bundle (it belongs in the .d.ts, which is
  // generated separately). Legal/annotation comments are still preserved.
  outputOptions: { comments: { jsdoc: false } },
  // Ship sourcemaps for both formats so consumers can debug into the published
  // artifact; attw/publint validate the emitted map references.
  sourcemap: true,
  treeshake: true,
});
